### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by aplcomp** [phar-io/phive#239] opened 2020-04-24 14:31 UTC
phive install theseer/Autoload
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    No RateLimit present in respons

**Comment by theseer** [comment] 2020-04-24 14:50
Duplicate of #228

**Closed by theseer** 2020-04-24 14:50 UTC
Labels: duplicate
