### ISSUE TITLE
All servers in the pool: Failed with error code 504: Server reported an error

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#184] opened 2019-03-31 09:49 UTC
```
$ phive install n98-magerun
Phive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://files.magerun.net/n98-magerun-1.102.0.phar
Downloading https://files.magerun.net/n98-magerun-1.102.0.phar.asc
Downloading key 59B3B8B6C924630C
Trying hkps.pool.sks-keyservers.net (192.146.137.99)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (37.191.231.105)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (51.38.91.189)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (46.4.246.179)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (192.146.137.98)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::99:0)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::98:0)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (2a01:4f8:222:2401:1::179)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
Trying hkps.pool.sks-keyservers.net (2001:41d0:800:d1e::82:0)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr
[WARNING]  Failed with error code 504: Server reported an error
[ERROR]    PublicKey 59B3B8B6C924630C not found on key servers
```

Please advise.

**Comment by szepeviktor** [comment] 2019-03-31 09:50
but

```
$ gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x59B3B8B6C924630C
gpg: key 59B3B8B6C924630C: "Christian Muench (Key to sign n98-magerun phar files.) <c.muench@netz98.de>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by theseer** [comment] 2019-03-31 10:25
I'm afraid, there's not really much we can do if the keyserver infrastructure is having issues. `504` is a server side http error.

To (hopefully) mitigate the problem, in commit 6b5b8874ca0a529d7e0713e1364f9b839df44797 the list of servers has been extended. Given those servers should be part of the sks server pool, those servers seem to be quite stable.

We're still debating, whether adding a server ourselves is going to help or would make it worse ;)

You can try to use phive's master branch to make use of the change before it's released.

I'm closing this issue. Please comment if you need it reopened.

**Closed by theseer** 2019-03-31 10:25 UTC

**Comment by szepeviktor** [comment] 2019-03-31 10:36
@theseer Thank you.

How come that the n98-magerun key is installed in the second comment?

**Comment by szepeviktor** [comment] 2019-03-31 10:53
and

```
$ $ wget -SqO- "https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr" --no-check-certificate
  HTTP/1.1 200 OK
  Date: Sun, 31 Mar 2019 10:53:25 GMT
  Content-Type: text/plain
  Content-Length: 179
  Connection: keep-alive
  Server: sks_www/1.1.6
  X-HKP-Results-Count: 1
  Access-Control-Allow-Origin: *
  X-Cache-Status: HIT
  Via: 1.1 fks.pgpkeys.eu (nginx)
info:1:1
pub:645986D30918EE4DB0D621E259B3B8B6C924630C:1:4096:1514889866:1546425866:
uid:Christian Muench (Key to sign n98-magerun phar files.) <c.muench@netz98.de>:1514889866::
```

**Comment by szepeviktor** [comment] 2019-03-31 10:54
@theseer If you will you could reopen this as some debugging may reveal the root cause.

**Comment by theseer** [comment] 2019-03-31 11:36
> How come that the n98-magerun key is installed in the second comment?

It's actually not: 
```
gpg:              unchanged: 1
```

**Comment by theseer** [comment] 2019-03-31 11:38
> @theseer If you will you could reopen this as some debugging may reveal the root cause.

There is no debugging to be done on our side. It's _server side_ issue at the sks server pools. `Phive` is getting HTTP/1.1 504 as a response code.

**Comment by theseer** [comment] 2019-03-31 11:40
> and
> 
> ```
> $ $ wget -SqO- "https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x59B3B8B6C924630C&op=index&options=mr" --no-check-certificate
>   HTTP/1.1 200 OK
>   Date: Sun, 31 Mar 2019 10:53:25 GMT
>   Content-Type: text/plain
>   Content-Length: 179
>   Connection: keep-alive
>   Server: sks_www/1.1.6
>   X-HKP-Results-Count: 1
>   Access-Control-Allow-Origin: *
>   X-Cache-Status: HIT
>   Via: 1.1 fks.pgpkeys.eu (nginx)
> info:1:1
> pub:645986D30918EE4DB0D621E259B3B8B6C924630C:1:4096:1514889866:1546425866:
> uid:Christian Muench (Key to sign n98-magerun phar files.) <c.muench@netz98.de>:1514889866::
> ```

Yes? So it works again. Looks like the problem is fixed. Or does the problem persist with `phive` while it works with wget/curl?

**Comment by szepeviktor** [comment] 2019-03-31 18:34
I cannot really believe that 9 different keyserver are down at the moment.
How could I get debug log?

```
viktor@mail:~/tmp/phive$ phive update
Phive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/theseer/autoload/releases
Downloading https://github.com/theseer/Autoload/releases/download/1.25.3/phpab-1.25.3.phar
Downloading https://github.com/theseer/Autoload/releases/download/1.25.3/phpab-1.25.3.phar.asc
Downloading key 2A8299CE842DD38C
Trying hkps.pool.sks-keyservers.net (46.4.246.179)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (192.146.137.98)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (51.38.91.189)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (37.191.231.105)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (192.146.137.99)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (2a01:4f8:222:2401:1::179)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::99:0)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::98:0)
[WARNING]  Failed with error code 502: Server reported an error
Trying hkps.pool.sks-keyservers.net (2001:41d0:800:d1e::82:0)
[WARNING]  Failed with error code 502: Server reported an error
[ERROR]    PublicKey 2A8299CE842DD38C not found on key servers
```

**Comment by szepeviktor** [comment] 2019-03-31 18:37
Also on Travis: https://travis-ci.org/phar-io/phive/jobs/513823138#L497 breaking the tests.
