### ISSUE TITLE
gpg error on phive installation

### ISSUE THREAD

**Issue by JamesRezo** [phar-io/phive#314] opened 2021-06-23 16:24 UTC
Hello,

At https://phar.io/#Install

`gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79`

returns `gpg: keyserver receive failed: No name` and fails

if  it  is usefull on mac os x `gpg --version` says  :

> gpg (GnuPG) 2.2.27
> libgcrypt 1.9.2

on ubuntu focal :

> gpg (GnuPG) 2.2.19
> libgcrypt 1.8.5

**Comment by theseer** [comment] 2021-06-23 18:15
Interesting. I cannot reproduce this:

```
theseer@nyda /tmp/x6 $ gpg -n -v --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79
gpg: data source: https://keys.openpgp.org:443
gpg: pub  rsa4096/9D8A98B29B2D5D79 2015-09-22  
gpg: Total number processed: 1
```

Works for me? Maybe a temporary issue?

```
gpg (GnuPG) 2.2.25
libgcrypt 1.8.7
```
The above is on Fedora 33

**Comment by JamesRezo** [comment] 2021-06-24 09:02
I found [an alternative](https://superuser.com/questions/1485213/gpg-cant-import-key-new-key-but-contains-no-user-id-skipped) for ubuntu focal :

`gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0x9D8A98B29B2D5D79`

**Comment by theseer** [comment] 2021-06-24 19:45
That's just using a different keyserver. Of course that should also work.

Our key on `keys.openpgp.org` though should have been fully registered, including UID.
I just reuploaded the key to verify that. It still works for me, but maybe that's also because I of course have the real key here already...

Maybe you can verify that again, but I believe this to be a non-issue by now and will thus close this.

**Closed by theseer** 2021-06-24 19:45 UTC

**Comment by theseer** [comment] 2021-06-24 19:48
```
theseer@nyda /tmp/x7 $ GNUPG_HOME=`pwd` ; gpg -n -v --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79
gpg: data source: https://keys.openpgp.org:443
gpg: armor header: Comment: 6AF7 2527 0AB8 1E04 D794  4254 9D8A 98B2 9B2D 5D79
gpg: armor header: Comment: phar.io <team@phar.io>
gpg: pub  rsa4096/9D8A98B29B2D5D79 2015-09-22  phar.io <team@phar.io>
gpg: Total number processed: 1
```

The output now is indeed different. So maybe the key on the openpgp.org server was actually borked.

**Comment by 4c0n** [comment] 2021-06-30 09:11
This was working for a little bit (using sks-keyserver), but now I'm experiencing the same problem again. How does the name get lost?

**Comment by theseer** [comment] 2021-06-30 09:15
No idea, but the sks keyservers are dead. Use `keys.openpgp.org`.

The UID is still there: `https://keys.openpgp.org/search?q=team%40phar.io`

**Comment by 4c0n** [comment] 2021-06-30 09:26
Thanks that works!
