### ISSUE TITLE
Issue with Psalm's signing

### ISSUE THREAD

**Issue by muglug** [phar-io/phive#176] opened 2018-12-15 15:39 UTC
I'm probably doing this all wrong, but I (creator of Psalm) submitted a public key to keyservers yesterday but `phive` doesn't seem to know it.

I get 
```
phive install --target . psalm
Phive 0.12.1 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/vimeo/psalm/releases
Downloading https://github.com/vimeo/psalm/releases/download/3.0.5/psalm.phar
Downloading https://github.com/vimeo/psalm/releases/download/3.0.5/psalm.phar.asc
Downloading key 8A03EA3B385DBAA1
Trying hkps.pool.sks-keyservers.net (46.4.246.179)
[WARNING]  Failed with error code 502: Server reported an error 
Trying hkps.pool.sks-keyservers.net (192.146.137.98)
[WARNING]  Failed with error code 502: Server reported an error 
Trying hkps.pool.sks-keyservers.net (192.146.137.99)
[WARNING]  Failed with error code 404: Key not found on keyserver 
Trying hkps.pool.sks-keyservers.net (37.191.231.105)
[WARNING]  Failed with error code 404: Key not found on keyserver 
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::98:0)
[WARNING]  Failed with error code 404: Key not found on keyserver 
Trying hkps.pool.sks-keyservers.net (2001:67c:26b4::99:0)
[WARNING]  Failed with error code 404: Key not found on keyserver 
Trying hkps.pool.sks-keyservers.net (2a01:4f8:222:2401:1::179)
[WARNING]  Failed with error code 404: Key not found on keyserver 
[ERROR]    PublicKey 8A03EA3B385DBAA1 not found on key servers 
```

But when pinging with `gpg` I get
```
gpg --keyserver pool.sks-keyservers.net --search-keys 8A03EA3B385DBAA1
gpg: data source: http://[::ffff:147.96.25.75]:11371
(1)	Matthew Brown <github@gmail.com>
	  2048 bit RSA key 8A03EA3B385DBAA1, created: 2018-12-14, expires: 2020-12-13
```

**Comment by theseer** [comment] 2018-12-17 15:22
Problem confirmed.

We're accessing the keyserver via http which seems to be a problem for some reason.
I'll be looking at it asap to figure out what causes this.

**Comment by muglug** [comment] 2018-12-17 15:36
Cc @ADmad

**Comment by ADmad** [comment] 2018-12-17 16:16
Good to know we figured out what's causing the problem :).

**Comment by theseer** [comment] 2018-12-17 16:36
It certainly seems to be a problem on phive's end (or rather how we talk to the keyservers)

**Comment by digilist** [comment] 2018-12-18 21:03
I noticed the same (or a similar?) issue just now within Docker. In my Docker container `phive install` always fails with the error from above when I try to install PHP-CS-Fixer (Key E82B2FB314E9906E).

So I tried to reproduce the error on my host machine and removed ~/.phive to have a clean setup. I got the same errors, but after running `phive install` multiple times it succeed eventually. However, in my Docker container it fails continuously.

**Comment by theseer** [comment] 2018-12-18 21:13
I'm convinced the sks-keyservers are having issues.

The results are fairly inconsistent and depend highly on what server or pool you end up at.

Right now, i have a few ideas how to address this:

a) For known aliases (like psalm) we add the public key into the repositories.xml (see #158)
b) Add additional explicit keyservers to the config (See https://github.com/phar-io/phive/issues/175#issuecomment-445838546)
c) Maybe we can also setup our own keyserver as a last resort


I personally don't like the option c very much as it would centralize the infrastructure to phar.io, which is exactly what we try very hard to avoid from happening. But maybe as a fallback that's fine, given that we sync the respostories.xml already anyhow.

**Comment by digilist** [comment] 2018-12-19 09:16
Just fyi: This morning it is now working for me without any problems again (even within Docker) :smile:

**Comment by theseer** [comment] 2018-12-19 21:05
Nice that it works for you again. Unfortunately the underlying issue remains so I'll keep this ticket open.

**Comment by ADmad** [comment] 2018-12-20 18:44
It's worked for me too.

```
$ phive install --target . psalm
Phive 0.12.1 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/vimeo/psalm/releases
Downloading https://github.com/vimeo/psalm/releases/download/3.0.5/psalm.phar
Downloading https://github.com/vimeo/psalm/releases/download/3.0.5/psalm.phar.asc
Downloading key 8A03EA3B385DBAA1
Trying hkps.pool.sks-keyservers.net (37.17.173.9)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x8A03EA3B385DBAA1&op=index&options=mr
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x8A03EA3B385DBAA1&op=get&options=mr
Successfully downloaded key

	Fingerprint: 5EAE 7E97 5CE1 510C 4F54 D4B0 8A03 EA3B 385D BAA1

	Matthew Brown <github@gmail.com> (2018-12-14)

	Created: 2018-12-14

Import this key? [y|N] y
```

**Comment by theseer** [comment] 2018-12-20 18:47
Glad it works again and it seems to have been a problem outside our control.

It convinces me more and more though to find an alternative solution like pointed out in https://github.com/phar-io/phive/issues/176#issuecomment-448372619.

I'll close this ticket.

**Closed by theseer** 2018-12-20 18:47 UTC
Labels: breaking
