### ISSUE TITLE
Not intuitive usage

### ISSUE THREAD

**Issue by glensc** [phar-io/phive#331] opened 2021-12-01 16:03 UTC
I was looking at how to specify a version to install specific version:

```
➔ phive install --help
Phive 0.15.0 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    Error while processing arguments to command 'install':
[ERROR]    Unknown option: help

➔ phive install -h
Phive 0.15.0 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    Error while processing arguments to command 'install':
[ERROR]    Unknown option: h
```

**Comment by glensc** [comment] 2021-12-01 16:25
One more example of unintuitive response:

```
phive install --target=bin/tools composer@^1.10 --force-accept-unsigned
```

why not use some standard commandline parsing like symfony/console?

**Comment by theseer** [comment] 2021-12-01 16:44
> One more example of unintuitive response:
> 
> ```
> phive install --target=bin/tools composer@^1.10 --force-accept-unsigned
> ```
> 
> why not use some standard commandline parsing like symfony/console?

Because symfony console is bloated and doesn't support global and command specific options.
And because I don't like the API.

**Comment by theseer** [comment] 2021-12-01 16:46
> I was looking at how to specify a version to install specific version:
> 
> ```
> ➔ phive install --help
> Phive 0.15.0 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
> [ERROR]    Error while processing arguments to command 'install':
> [ERROR]    Unknown option: help
> 
> ➔ phive install -h
> Phive 0.15.0 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
> [ERROR]    Error while processing arguments to command 'install':
> [ERROR]    Unknown option: h
> ```

Duplicate of #253

**Closed by theseer** 2021-12-01 16:46 UTC
