### ISSUE TITLE
Allow insecure installation of phar files

### ISSUE THREAD

**Issue by djmattyg007** [phar-io/phive#134] opened 2018-03-26 21:45 UTC
It would be nice to be able to use phive to manage the installation of any phar file, not just those that are signed with PGP keys.

**Comment by theseer** [comment] 2018-03-26 21:57
That kind of defeats the purpose of phive, doesn't it?

**Comment by djmattyg007** [comment] 2018-03-27 07:27
I don't agree. Phive does a wonderful job of automating the process of updating and verifying phar files for those that are signed with PGP keys. However, I'm still going to use some phar files from vendors that I trust that aren't signed with PGP keys.

If Phive doesn't support this use case, I'm more likely to forgo Phive entirely and instead write a custom script to run wget to obtain all the phar files I need. This increases the chances of me getting the PGP signature verification wrong, as I also have to run those commands manually.

The point is that an all-or-nothing approach is not particularly helpful. Whether or not something supports installation by Phive isn't going to prevent someone from using that tool, so you're better off supporting more use cases so that the end user still benefits from the advantages brought by Phive at least a little bit.

**Comment by theseer** [comment] 2018-03-27 10:53
Okay, point taken.

**Comment by djmattyg007** [comment] 2018-03-27 14:40
I'd be happy to work on a PR for this functionality. Is there anything I shoukd know before I get to work?

**Comment by theseer** [comment] 2018-03-27 14:59
Awesome!  If you have any questions, do not hesitate to contact us by email or write in this ticket.

I don't think there's very much to know. The code should be pretty self-explanatory.

Though, I have a few thoughts/wishes/idea:

- Maybe obvious: the default behavior of phive should be the secure mode
- Insecure installation must be requested by an additional cli option
- I'd prefer a naming for that option that makes it clear it's an undesired thing like `--force-insecure` rather than `--ignore-errors`
- We probably want to record that decision in the phive.xml
- When installing from phive.xml with insecure phars, the same option needs to be given or interactively confirmed. If no interaction is possible, we should probably abort the installation

**Comment by djmattyg007** [comment] 2018-04-02 22:50
I've been playing around with it for the last week, and I have a few notes that I wanted to record here:

1. I think `--allow-insecure` is the best name for the flag, the reasons for which should become clear below.
2. For the sake of specificity, use of the `--allow-insecure` flag is not designed to allow downloads to occur over insecure HTTP.
3. If the user is installing a phar that has never been installed before and is not in the registry, even if the user passes the `--allow-insecure` flag, we should still attempt to verify the file. The `--allow-insecure` flag should simply permit verification to fail. This will hopefully protect the user in case they accidentally pass that flag unnecessarily.
4. I don't think that unverified phar files should be saved to the registry.
5. However, if they are saved to the registry, the fact that they were not verified will need to be recorded. In this case, installation of unverified phar files from the registry will require the `--allow-insecure` flag.

What are your thoughts?

**Comment by theseer** [comment] 2018-04-03 12:10
For readability reasons, let me respond to each item of your list individually:

1.  I'm not convinced we have the right name yet. We want it to express that it has (generally unwanted) security implications and only affects the gpg check, not the transfer.

2. I do fully agree. HTTPS is not negotiable and it should not be possible to disable it.

3. I'm unsure whether I understand this correctly. What do you mean by registry? Our local `~/.phive/phars.xml`-storage? If it's there, it's there. We do not recheck things. We might consider providing a means to commit local phar files to that storage, but that's a different topic. "Allowing verification to fail" is fairly unspecific and the way I understand it feels wrong: If I do run a verification, it *has* to pass. We can argue - and that's what this ticket is probably about ;) - whether or not to attempt the verification in the first place.

4. Again, what's the registry here? The `phars.xml` or the `phive.xml` file. Either way, the user is in charge. If we allow non-checked phars to be used, it's the users responsibility to deal with the consequences. We might mark the installation as "tainted" to highlight that fact actually. Redownloading them every time kills the idea of phive, so we have to store them somehow. Also, if you want to be able commit the projects phive.xml, we need to have a full set of phars installed - not only the ones that got checked. So again, we need to store that somehow. So I guess, I disagree ;)

5. I currently would say the "tainted" flag merely gets moved along. Meaning, if we have a tainted flag or any other marking for the phar in the `phars.xml`, we should add the same mark to the `phive.xml` entry. 

My answer to 5 opens up new questions:
- Do we silently accept insecure phars based on the flag when `phive install` is performed? 
- What about `phive update`?
- What do we do with inconsistencies, e.g. a local phars.xml having an insecure entry for a phar that according to the `phive.xml` should have been checked?

**Comment by djmattyg007** [comment] 2018-04-04 22:56
Sorry for not making it clearer about what the registry is. In the code, there is a class named `PharRegistry` that appears to be responsible for managing what's in `~/.phive`. That would include `phars.xml`, and is what I was referring to. I'll do my best to avoid such confusion going forward :)

I think the name `--allow-insecure` is more appropriate than `--force-insecure` for a couple of reasons:

1. Someone may specify it for the `phive install` command even when no phar files are going to be downloaded and no phars in `phive.xml` are marked as insecure.
2. Someone may have incorrectly marked a phar that is definitely verifiable as insecure in `phive.xml`. If we still performed the verification in this case, it would succeed, and we wouldn't need to print a warning for the user.

However I agree that it doesn't do a good enough job of communicating the fact that this is solely for signature verification. What about something verbose such as `--force-allow-insecure-installations`? This includes the word "installations", which is separate from "downloads". It also includes the word "force", which I would definitely like to include if possible (I do find that people tend to be a bit cautious with actions that require "forcing" something).

Also, having had time to reflect on what you wrote regarding expecting signature verification to succeed, I have changed my mind and agree with you. In fact I think you could make an argument that what I was suggesting is actually dangerous. I'm fine with saving unverified phars to `phars.xml`. I agree that we need to record the fact that verification did not happen, and do like the word "tainted" for this. What do you think about preventing insecure installations for phars that come from the phar.io repository though? We know ahead of time that these should always be signed.

To answer the questions at the end of your message:

1. I definitely think we should always print a warning when the insecure flag is passed.
2. `phive update` appears to make use of a lot of the same services as `phive install`, so I guess it will need the same flag.
3. I think the only suitable course of action in this case is to reject the request.
    1. If `phars.xml` says a phar is tainted and `phive.xml` isn't marked as allowing insecure installations for that phar (or the user is attempting to install it for the first time using `phive install phar-identifier`), the user will potentially get a tainted installation without realising it. We must reject it.
    2. If `phars.xml` says a phar is not tainted, then there is no need to force an insecure installation either from `phive.xml` or with `phive install phar-identifier`.

**Comment by theseer** [comment] 2018-04-11 18:40
Sorry for the delay in replying, been a busy week.

> What about something verbose such as --force-allow-insecure-installations? 

The combination "Force allow" sounds weird. It's not really "allowing" either if it's forced. I like the verbose though ;)

Let's see how others do that:
- DNF (Fedora) and YUM (CentOS/RHEL) use `--nogpgcheck`
- Apt (Debian) has `--allow-unauthenticated`
- Zypper (SuSE) has `--no-gpg-checks`

I didn't find any pointers for Ubuntu.
I don't like either of these ;) but the general direction of obviously "disabling" something.

Long story short: How about: `--disable-gpg-signature-check` for us? Verbose and clear, maybe even without the `gpg` in case we support other means at some point.

While pondering whether that would be singular or plural (-checks), I came up with the question if we maybe want to explicitly require this to be singular? As in require to install insecure phars one by one, making it a deliberate decision for each? 

> What do you think about preventing insecure installations for phars that come from the phar.io repository though? We know ahead of time that these should always be signed.

Do we? Technically, there is no such thing as a phar.io repository. All we do is provide a list of aliases pointing to the location where to get the actual phar. Much like a nameserver in the DNS world does.
Even if I refuse to merge PRs against the repository list when the to be added alias does not point to signed phars, we do not have any influence whether or not later releases will be signed. 

I otherwise agree with your conclusions :)

How do we proceed from here?

**Comment by theseer** [comment] 2018-04-14 15:39
I totally agree with `phive status` needing to show the verification state and thanks a lot for bringing that up.

I do not like the Debian "allow"-tonality as I want to make it explicit that something is taken away rather than enabled when the flag is specified.

I agree the `--disable-gpg-signature-check` may sound like it's for all phars but I don't see that as a problem per se: The switch should only be available when the `install` command is used in combination with a single phar alias or url, effectively forcing the user to explicitly disable security on a per phar basis when initially installing. Given that this decision is recorded in the phive.xml, any run with `phive install` would honor that decision - for example in a CI context. Same goes for `phive update`.

**Comment by ThomasWeinert** [comment] 2018-04-14 19:03
If the phive.xml is committed into the repository the user that later calls `phive install/update` can be different. He/she did not make that decision yet. Rather then saving the decision, I would require it for each call.

**Comment by theseer** [comment] 2018-04-25 12:00
I spent some time thinking about this and I'm not sure what the best approach is.
Let me spill out some of my thoughts:

Once downloaded and possibly checked, we currently do not re-verify a phar.  We simply symlink an existing matching version whenever possible. So unless we somewhere store that the file had been successfully verified, we will never know the difference. Showing the key id that was used to check the signature may be a pointer for the user but is too indirect for me.

If I'm to add a phar that does not come with a verifiable signature to a project and have means to commit the phive.xml, I'm inclined to say that decision is made on behalf of the project. It is an unlikely edge case that the verification will magically work on a different host than mine. So for that, I want that decision to be transparent - read: stored - and an easy means to install all entries from the phive.xml.

That of course leaves a logical loophole: Given that this way an unverified phar will be available for explicit installation (since it's in the local phar db) we need to make sure to enhance the install process to check whether or not the phar had been verified before and complain in case it's to be added to a new project unless the switch to disable the check has been passed.

I stick to my proposal of `--disable-gpg-signature-check` for that.

**Comment by theseer** [comment] 2018-04-25 18:49
I didn't say that but I admit that my previous reply may not have made that very clear.
Let me try to rephrase, and extend my statement after thinking some more.

My idea is to require `--disable-gpg-signature-check` to add a phar without performing a gpg check. Only a single phar could be installed that way at a time. The fact it has been added to the project in an insecure way will be recorded in the `phive.xml` (project) as well as `phars.xml` (phar storage). When running `phive install` for a project and the phar is not already in the local database, we'll handle them as usual. Meaning, unknown keys for signed phars will be imported  - after confirmation - as before. Insecure phars will also require confirmation but do not require the disable switch.

Thinking of it, we might want to add a logical counterpart to `--trust-gpg-keys` for that mode to make the installation of unsigned phars completely non-interactive.

Does that make sense? :)

**Comment by ThomasWeinert** [comment] 2018-05-14 09:37
I dislike '--disable-gpg-signature-check' because it sounds like it would ignore the signature for signed phars, too.

How do you want to handle it in the CI?

**Comment by Aerendir** [comment] 2018-06-09 10:05
@theseer , I agree with all your points in https://github.com/phar-io/phive/issues/134#issuecomment-376557599 but the last.

A tool like this may be used in a continuous integration system where the interaction is not possible: maybe a flag like the classic `--no-interaction` could be better.

This will allow to use Phive also on CI servers and it could be very useful also in such scenario...

**Comment by theseer** [comment] 2018-06-09 10:20
@Aerendir, thanks for the additional input.

I by no means meant to stop Phive from being usable in CI scenarios. Maybe the wording wasn't optimal but the idea is (or was at least) that, in case the phive.xml contains unsigned phars, instead of silently installing them, the _same_ switch that was initially used to install unsigned phars needs to be used again.

**Comment by Aerendir** [comment] 2018-06-09 10:49
@theseer , ok, now it is more clear! :)

**Comment by theseer** [comment] 2018-06-09 11:13
New idea for the switch: `--accept-unsigned-phars`. 

While I'm still not happy with the "positiveness" of it, it represents exactly what it does.

**Comment by Aerendir** [comment] 2018-06-09 11:42
I liked a lot the idea of `--force-*` because make clear the forcing of something that is well accepted.

Maybe `--force-accept-unsigned`: the `phar` part is implicitly meant as we are speaking about a package that manages phar files...

**Comment by Aerendir** [comment] 2018-06-11 08:48
I've just seen, thanks to [this comment](https://github.com/phan/phan/issues/1759#issuecomment-396014725), that there is a flag `--trust-gpg-keys`: maybe a flag like `--trust-package` can also be a good option.

This way each package without a GPG key must be explicitly listed (and this is a pain that hopefully will force devs to add their own GPG keys), a sort of homogeneity is maintained around flags and the goal is anyway reached.

**Comment by theseer** [comment] 2018-06-23 17:41
After spending again quite some time pondering the suggested names for the switch in the back of my head, I think I don't like the `--trust-package` suggestion because it doesn't reflect enough it's an unwanted situation.

Providing a set of gpg identifiers to be considered trusted is perfectly sane and as far as I can tell does have no impact on security. Read: From a security perspective, there is not really a difference between manually accepting a suggested key during its first appearance within the installation or telling phive to accept a key if it's the one expected upfront.

Installing an unsigned phar on the other hand _has_ a security impact and I want that to be every clear.

So my vote stays with `--force-accept-unsigned`.

@djmattyg007 Do you still feel like working on this?

**Comment by Aerendir** [comment] 2018-06-23 21:10
Then, it'll be `--force-accept-unsigned`! :)

**Comment by theseer** [comment] 2018-07-03 13:33
@djmattyg007 ping?

**Comment by theseer** [comment] 2018-07-06 22:09
Implemented so far:
- Added switch `--force-accept-unsigned` to install and update commands
- Added support for unsigned phars via Github releases

Pending:
- Support for unsigned phars via direct URL
- Decision if the forced state should be recorded

**Comment by ThomasWeinert** [comment] 2018-07-06 22:34
> Decision if the forced state should be recorded

I would see that as a double lock for the CI. `phive install --no-interaction --force-accept-unsigned` would only work for unsigned phars installed with the flag. Not sure if that is needed.

**Comment by theseer** [comment] 2018-07-16 20:37
Support for unsigned phars added with commit b81b72c2e6b1d32844a8f5ac8258e42ed335d0db

**Comment by theseer** [comment] 2018-07-16 20:42
When not recording the forced state, trying to reinstall based on phive.xml on another system will have to specify `--force-accept-unsigned` as well.

Recording is not currently implemented and I lean to give it a try. If it turns out to be annoying or there are good reasons why having it recorded (and imply --force-accept-unsigned for those), we might open a new ticket for it.

Considering the topic of this ticket implemented.

**Closed by theseer** 2018-07-16 20:42 UTC
Labels: enhancement

**Comment by XedinUnknown** [comment] 2025-07-30 10:46
`--force-accept-unsigned` still fails if GPG is not installed. 

```
$ phive --no-progress install --force-accept-unsigned <my-repo>
Phive 0.16.0 - Copyright (C) 2015-2025 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    No executable gpg binary found.  
[ERROR]     Either install gpg or enable the gnupg extension in PHP.
```
