### ISSUE TITLE
Undefined array key 'SERVER_PORT' updating package

### ISSUE THREAD

**Issue by hdfelix** [phar-io/phive#315] opened 2021-07-02 17:01 UTC
Trying to Update php-cs-fixer:

```
$ phive update php-cs-fixer
```

Output:

```
Phive 0.14.5 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.19.0/php-cs-fixer.phar
Downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.19.0/php-cs-fixer.phar.asc
Linking /Users/hector/.phive/phars/php-cs-fixer-2.19.0.phar to [project-directory]

[ERROR]    An error occurred while processing your request:

          Undefined array key "SERVER_PORT"
          
          #0 (1)
          #1 unknown file(0): PharIo\Phive\Cli\Runner->shutdownHandler()
          #2 {main}

          Environment: PHP 8.0.2 (on Darwin 18.7.0)
          Phive Version: 0.14.5

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

**Comment by theseer** [comment] 2021-07-02 18:33
Thanks for reporting this.

The "crash" appears to happen in the shutdown handler because that's where we catch "unknown" errors and apparently something is trying to access an array element `SERVER_PORT`. So far, so obvious ;)

I have to admit though, I'm at a total loss as to what might be triggering this. There is literally no code requesting that key:

```
phive master $ grep -r  "SERVER" src vendor

src/shared/environment/UnixoidEnvironment.php:        return new static($_SERVER, new Executor());
src/shared/environment/Environment.php:        return new static($_SERVER);
```

I also cannot reproduce this on Linux:

```
theseer@nyda /tmp/x2 $ phive --home ./home update php-cs-fixer
Phive 0.14.5-12-gba7525b-dirty - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/FriendsOfPHP/PHP-CS-Fixer/releases
Downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.19.0/php-cs-fixer.phar
Downloading https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.19.0/php-cs-fixer.phar.asc
Linking ./home/phars/php-cs-fixer-2.19.0.phar to /tmp/x2/tools/php-cs-fixer
```

Do you happen to have any additional pointers for me?

**Comment by theseer** [comment] 2021-07-24 19:49
Ping @hdfelix

**Comment by theseer** [comment] 2022-03-23 22:18
No Feedback provided. Closing.

**Closed by theseer** 2022-03-23 22:18 UTC
