### ISSUE TITLE
release 0.14 install breaks on windows

### ISSUE THREAD

**Issue by jaapio** [phar-io/phive#265] opened 2020-06-08 20:45 UTC
it is a bit unclear to me why this actually happens. But in github actions gpg keys cannot be downloaded via phive. I tried this on a windows vm with windows 10 installed. There phive does just work...

```
Run phive --no-progress --home $GITHUB_WORKSPACE/.phive install --copy --trust-gpg-keys 4AA394086372C20A,D2CCAC42F6295E7D,E82B2FB314E9906E,8A03EA3B385DBAA1 --force-accept-unsigned
Phive 0.14.3 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching repository list
Downloading https://phar.io/data/repositories.xml
Downloading https://phar.phpunit.de/phive.xml
Downloading https://phar.phpunit.de/phpunit-8.4.3.phar
Downloading https://phar.phpunit.de/phpunit-8.4.3.phar.asc
Downloading key 4AA394086372C20A
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x4AA394086372C20A
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 0: No UIDs in key found
Trying to connect to keyserver.ubuntu.com (162.213.33.8)
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 0: No UIDs in key found
Trying to connect to hkps.pool.sks-keyservers.net (192.146.137.141)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&options=mr&search=0x4AA394086372C20A
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 0: No UIDs in key found
[ERROR]   PublicKey 4AA394086372C20A not found on key servers

##[error]Process completed with exit code 1.
```
when doing the same thing, with same commands and env with phive 0.13.3 it just works.

**Comment by theseer** [comment] 2020-06-11 19:51
Does this problem still persist?

I cannot reproduce this on my windows VMs so far either. If the problem still exists, I  guess i'll have to setup a github action on a windows instance to see if i can somehow debug this.

**Comment by theseer** [comment] 2020-06-12 10:40
Would you actually feel like providing a github action setup for phive on windows? ;-)

**Comment by jaapio** [comment] 2020-06-12 14:43
Yes, this problem still persists. 

what would you like the github action to do? Execute phive with an installation of phpunit? As some kind of smoke test on all supported php versions and operating systems?

**Comment by theseer** [comment] 2020-06-12 18:58
Good question :-)

I guess we should setup a build matrix. It should include all supported operating systems as well as all types of resolvers (alias, github, gitlab and plain https url). For the alias resolver, we probably should also try the sub-types: As in, a type that resolves against github / gitlab / and phar.io repository type - like phar.phpunit.de. I don't think we currently have an alias that resolves to gitlab though.

While phpunit would certainly work, i'd go for something smaller so not to use more bandwidth than needed.

Once someone provides a "private" repository, we could also test for authentication of all our newly supported auth types.

The more I think about it, the bigger that matrix gets ;)

What do you say?

**Comment by jaapio** [comment] 2020-06-25 19:14
@theseer in my PR about the smoke test you mentioned something about a special prepared debug phive phar. Is there anything I can do to help you with that? Because I would love to have the issue fixed of course. But most important motivation is that I really want phive to be a better product. Because I believe that this is a missing piece in the php-world

**Comment by theseer** [comment] 2020-06-25 19:16
I'm at it. Give me a few minutes :)

**Comment by theseer** [comment] 2020-06-25 19:38
Okay, created a custom phar with a very chatty gnupg shim layer. Make sure you do not have `ext/gnupg` installed - which shouldn't be a problem for windows because it doesn't exist as far as i know.

Anyhow, get it from https://phar.io/debug-phive.phar and let me know when you had a run with it.

__Note to others who might be reading along here: This is *not* a release version you should be using for anything. It's merely provided to debug a this very specific issue and will most likely not help any of your problems__

**Comment by jaapio** [comment] 2020-06-25 19:52
Here you go:
https://github.com/phpDocumentor/phpDocumentor/runs/808753721?check_suite_focus=true

**Comment by jaapio** [comment] 2020-06-25 19:56
Just thinking right now... could it be a permission issue? We do use a `--home` flag, not 100% sure what that does on the github actions.

**Comment by jaapio** [comment] 2020-06-25 20:04
Got it... it was the cache... we used `phive --no-progress --home ${{ env.phiveHome }} ` where this environment variable was a path relative to the workspace, but for some reason this failed on windows...
Removing the `--home` did make the build pass! 

Think the only improvement on the phive side would be a better error report?

**Comment by theseer** [comment] 2020-06-25 20:05
Looks like i should also catch the error output rather than redirecting it to nul ;)

Hold on a sec.

**Comment by theseer** [comment] 2020-06-25 20:12
I guess instead of directly parsing the output we should probably also consider the exit code from gpg, which we currently ignore. Looking at it, that feels kind of ... risky ;)

**Comment by jaapio** [comment] 2020-06-25 20:14
Do you want me to provide a test case on https://github.com/phar-io/gnupg? I guess that's the most isolated location to do so?

**Comment by theseer** [comment] 2020-06-25 20:24
If you can be reproduced without `phive` "around" it, then yes, please.

**Comment by theseer** [comment] 2020-06-25 20:26
We probably also have to enhance `phar-io/executor` to provide `stderr` output, if any. I'll add a ticket for that.

**Comment by jaapio** [comment] 2020-06-25 20:35
Going to have a look to create a proper test case for this issue. Hopefully, I have time to do this tomorrow. If I cannot get it finished today :-)

**Comment by theseer** [comment] 2022-03-23 22:26
I guess after two years there won't be anything happening here anymore. Particularly given there was nothing to improve in Phive itself here.

I'll thus close this. Please open a new issue or comment if you feel this is the wrong move.

**Closed by theseer** 2022-03-23 22:26 UTC
