### ISSUE TITLE
phive selfupdate doesn't seem to work.

### ISSUE THREAD

**Issue by ADmad** [phar-io/phive#240] opened 2020-04-26 16:09 UTC
Running `phive selfupdate` resulted in:

```
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    No RateLimit present in response 
```

**Comment by theseer** [comment] 2020-04-26 17:21
Duplicate of #228

**Closed by theseer** 2020-04-26 17:21 UTC
Labels: duplicate

**Comment by ADmad** [comment] 2020-04-26 18:06
Sorry for the duplicate.

**Comment by theseer** [comment] 2020-04-26 18:16
No worries :)
