### ISSUE TITLE
Exception while installing PHPUnit

### ISSUE THREAD

**Issue by zf2timo** [phar-io/phive#147] opened 2018-06-19 13:42 UTC
Hi there,

I tried to install PHPUnit with PHIVE in a Docker Container. 
Exception Message:
```bash
root@1741a739277d:/# phive install phpunit
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://phar.phpunit.de/phive.xml
Downloading https://phar.phpunit.de/phpunit-7.2.4.phar
Downloading https://phar.phpunit.de/phpunit-7.2.4.phar.asc
Downloading key 4AA394086372C20A
Trying hkps.pool.sks-keyservers.net (216.66.15.2)
Successfully downloaded key
[ERROR]    An error occurred while processing your request:

          Call to a member function format() on null
          
          #0 har:///usr/bin/phive/src/services/key/PublicKey.php(68)
          #1 har:///usr/bin/phive/src/services/key/KeyService.php(69): PharIo\Phive\PublicKey->getInfo()
          #2 har:///usr/bin/phive/src/services/signature/gpg/GnupgSignatureVerifier.php(40): PharIo\Phive\KeyService->importKey()
          #3 har:///usr/bin/phive/src/services/phar/PharDownloader.php(109): PharIo\Phive\GnupgSignatureVerifier->verify()
          #4 har:///usr/bin/phive/src/services/phar/PharDownloader.php(61): PharIo\Phive\PharDownloader->verifySignature()
          #5 har:///usr/bin/phive/src/services/phar/PharService.php(38): PharIo\Phive\PharDownloader->download()
          #6 har:///usr/bin/phive/src/services/phar/InstallService.php(68): PharIo\Phive\PharService->getPharFromRelease()
          #7 har:///usr/bin/phive/src/commands/install/InstallCommand.php(57): PharIo\Phive\InstallService->execute()
          #8 har:///usr/bin/phive/src/commands/install/InstallCommand.php(44): PharIo\Phive\InstallCommand->installRequestedPhar()
          #9 har:///usr/bin/phive/src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #10 har:///usr/bin/phive/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #11 usr/bin/phive(300): PharIo\Phive\Cli\Runner->run()
          #12 {main}

          Environment: PHP 7.1.17-0ubuntu0.17.10.1
          Phive Version: 0.10.0
```

The container is an empty ubuntu 17.10 with a few applications installed:
```Dockerfile
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends ca-certificates dirmngr gnupg openssl wget \
    php php-curl php-dom php-mbstring
```
I assume there was a timeout during the key download. This step took a lot of time.

**Comment by theseer** [comment] 2018-06-21 05:51
Looks indeed like we have issues detecting network issues.

Interesting, since curl should do that for us. I currently have no idea how to forcibly reproduce to be able to debug this. Any ideas?

**Comment by zf2timo** [comment] 2018-06-21 06:48
Maybe you can reproduce the Issue when using the Container:

```Dockerfile
FROM ubuntu:17.10
MAINTAINER Timo Tewes <timo.tewes@celexongroup.com>

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends ca-certificates dirmngr gnupg openssl wget \
    php php-curl php-dom php-mbstring

COPY scripts/installation/phive.sh /root/phive.sh

RUN chmod +x /root/phive.sh
RUN /root/phive.sh
```
`scripts/installation/phive.sh`:
```bash
#!/usr/bin/env bash

wget -O phive.phar https://phar.io/releases/phive.phar
wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
gpg --verify phive.phar.asc phive.phar
chmod +x phive.phar
mv phive.phar /usr/bin/phive
```
To build and run the container, I use these commands:
```bash
$ docker build -t static-coding-analyses . 
$ docker run -it static-coding-analyses bash
root@1741a739277d:/# phive install phpunit
```

**Comment by theseer** [comment] 2018-06-22 08:11
Good idea, unfortunately it didn't work ;)
Funny enough, I believe I ran into the same problem already while building the image:

```
[...]
gpg: directory '/root/.gnupg' created
gpg: new configuration file '/root/.gnupg/dirmngr.conf' created
gpg: new configuration file '/root/.gnupg/gpg.conf' created
gpg: keybox '/root/.gnupg/pubring.kbx' created

{ here it hangs for quite a while }

gpg: keyserver receive failed: No data
gpg: Signature made Sun Mar 25 15:26:18 2018 UTC
gpg:                using RSA key 9D8A98B29B2D5D79
gpg: Can't check signature: No public key

 ---> 1d5ca81fa070
Removing intermediate container 9f9cb1922a1e
Successfully built 1d5ca81fa070
```

Since the container is technically already build, i ran it anyway and installation worked fine:
```
root@2c7830183d0c:/# phive install phpunit
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching respository list
Downloading https://phar.io/data/repositories.xml
Downloading https://phar.phpunit.de/phive.xml
Downloading https://phar.phpunit.de/phpunit-7.2.6.phar
Downloading https://phar.phpunit.de/phpunit-7.2.6.phar.asc
Downloading key 4AA394086372C20A
Trying hkps.pool.sks-keyservers.net (37.191.226.104)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=get&options=mr
Successfully downloaded key

	Fingerprint: D840 6D0D 8294 7747 2937 7831 4AA3 9408 6372 C20A

	Sebastian Bergmann <sebastian@php.net> (2014-07-19)
	Sebastian Bergmann <sebastian@thephp.cc> (2014-07-19)
	Sebastian Bergmann <sebastian@phpunit.de> (2014-07-19)
	Sebastian Bergmann <sb@sebastian-bergmann.de> (2014-07-19)
	Sebastian Bergmann <sebastian.bergmann@thephp.cc> (2014-07-19)
	Sebastian Bergmann <sebastian.bergmann@bbp-consulting.com> (2017-01-10)

	Created: 2014-07-19

Import this key? [y|N] y
Linking /root/.phive/phars/phpunit-7.2.6.phar to /tools/phpunit

root@2c7830183d0c:/# 
```

So far, I fail to find a way to forcibly reproduce this.

**Comment by theseer** [comment] 2018-06-22 08:16
Just to be clear: I do agree there to be a bug.
The reason why I want to be able to reproduce this first is that I'm not convinced that the line the crash happens at is the actual culprit: It shouldn't even get to that line to begin with if the key download didn't work. And I'd like to have a testcase to use for regression testing.

**Comment by theseer** [comment] 2018-06-23 17:46
Looks like I ran into this before: This is actually a duplicate of #130.

Given we have more input in here, I'll close the other ticket.

**Closed** 2018-06-26 13:45 UTC

**Comment by zf2timo** [comment] 2018-07-10 13:37
@theseer 
Thank you. Your fix solved my issue.
